FROM ruby:3.3-slim

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev git curl libvips libyaml-dev pkg-config && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV BUNDLE_PATH=/app/vendor/bundle

COPY Gemfile Gemfile.lock* ./
RUN bundle install

CMD ["bin/rails", "server", "-b", "0.0.0.0"]
